plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.0'
}

group = 'com.palm1.analoglib'
version = '1.2.0'

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', '../common/src/main/java']
            include 'com/palm1/analoglib/lavaplayer/**'
            include 'com/palm1/analoglib/client/audio/api/IRadioStreamer.java'
            include 'com/palm1/analoglib/client/audio/api/IPlaylistResolver.java'
            include 'com/palm1/analoglib/api/IAudioFilter.java'
            include 'com/sedmelluq/discord/lavaplayer/**'
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://maven.lavalink.dev/releases" }
    maven { url "https://repo.u-team.info" }
}

dependencies {
    implementation "net.hycrafthd.lavaplayer:lavaplayer:2.2.4-fix-j8"
    implementation "dev.lavalink.youtube:v2:1.16.0"
    implementation "org.slf4j:slf4j-api:2.0.9"
    
    compileOnly "org.lwjgl:lwjgl-openal:3.3.3"
    compileOnly "org.lwjgl:lwjgl:3.3.3"
}

shadowJar {
    archiveClassifier.set('')
    
    exclude "com/palm1/analoglib/config/**"
    exclude "com/palm1/analoglib/integration/**"
    exclude "com/palm1/analoglib/client/audio/api/**"

    mergeServiceFiles()
    
    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'
    exclude 'META-INF/LICENSE*'
    exclude 'META-INF/NOTICE*'
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jar.enabled = false
tasks.build.dependsOn shadowJar
